#!/bin/bash

src="$(basename $0).c"      # get the name of the program without ./ and append .c
executable="$(basename $0)"

function cleanup {
    # delete temporary files if they exist
    eval 'directory=($(ls /tmp | grep "object-files"))'
    if [ "$directory" != "" ]; then
        rm -f /tmp/object-files/${executable}
        rmdir /tmp/object-files
    fi
    exit 0
}
trap cleanup SIGINT SIGHUP SIGQUIT SIGTERM 0


mkdir /tmp/object-files/
gcc -std=c11 -ggdb $src -o /tmp/object-files/${executable}

args=""

for arg in $@
do
    args="$args $arg"
done

# execute the executable
/tmp/object-files/${executable} $args


